version: '3.7'

services:
  db:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    image: gin-mysql-image
    container_name: gin-db-container
    ports:
      - '3306:3306'
    volumes:
      - gin-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env

  api:
    build: .
    image: gin-api-image
    container_name: gin-api-container
    tty: true
    command: sh -c "cd api && air"
    ports:
      - '8080:8080'
    volumes:
      - .:/go/src/app
    depends_on:
      - db

  proxy:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    image: gin-nginx-image
    container_name: gin-proxy-container
    ports:
      - '8020:8020'
    depends_on:
      - api

volumes:
  gin-mysql-data:
