settings:
  legacy:
    force: true
    interval: 0s
server:
  status: true
  open: true
  port: 8020
  host: localhost
schema:
- name: api
  path: .
  commands:
    install:
      status: true
      method: go build -o main
    run:
      status: true
      method: ./main
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
