version: '3'

services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    image: 'gin-mysql-image'
    container_name: 'gin-db-mysql'
    volumes:
      - gin-mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: 'gin-api-image'
    container_name: 'gin-api'
    volumes:
      - .:/go/src/app
      - ./vendor:/go/src/app/vendor
    ports:
      - '8020:8020'
    tty: true

  proxy:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    image: 'gin-nginx-image'
    container_name: 'gin-proxy'
    ports:
      - '80:80'
    depends_on:
      - 'api'

volumes:
  gin-mysql-data:
  vendor:
