version: '3.7'

services:
  db:
    build:
      context: ./docker/mysql
      dockerfile: ./Dockerfile
    image: gin-mysql-image
    ports:
      - '3306:3306'
    volumes:
      - gin-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: gin-api-image
    tty: true
    ports:
      - '8020:8020'
    volumes:
      - .:/go/src/app
    environment:
      GO111MODULE: 'on'
    env_file:
      - .env
    depends_on:
      - db

  # proxy:
  #   build:
  #     context: ./docker/nginx
  #     dockerfile: ./Dockerfile
  #   image: gin-nginx-image
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - api

volumes:
  gin-mysql-data:
